name: lucid-from-html
version: '0.2.0'
synopsis: Tool to convert HTML to Lucid code.
description: ! 'Tool that converts HTML files to Haskell code, ready to be

  used with the Lucid library.'
category: Text
author: Oleg Tsybulskyi, David Baynard, Jasper Van der Jeugt, Simon Meier
maintainer: alogic0@gmail.com
license: BSD3
github: alogic0/lucid-from-html
dependencies:
- base >=4 && <5
- containers >=0.3
- directory >=1.0
- filepath >=1.1
extra-source-files:
- CHANGELOG.md
- README.md
ghc-options: -Wall
library:
  exposed-modules:
  - Lucid.Generate
  - Lucid.Sanitize
  - Lucid.Combinators
  source-dirs:
  - src
  dependencies:
  - tagsoup >=0.10
executables:
  lucid-from-html:
    source-dirs:
    - app
    main: Main.hs
    dependencies:
    - lucid-from-html
stability: Experimental
